public enum ESLDPartsTypes {
    APP_SPRLAYOUT_PARTS_TYPE_NONE = 0,
    APP_SPRLAYOUT_PARTS_TYPE_DUMMY = 1,
    APP_SPRLAYOUT_PARTS_TYPE_PARTS = 2,
    APP_SPRLAYOUT_PARTS_TYPE_RESOURCE = 3,
    APP_SPRLAYOUT_PARTS_TYPE_MAX = 4,
};

public enum ESLDResTypes {
    APP_SPRLAYOUT_RESOURCE_TYPE_NONE = 0,
    APP_SPRLAYOUT_RESOURCE_TYPE_SPR = 1,
    APP_SPRLAYOUT_RESOURCE_TYPE_TEXTURE = 2,
    APP_SPRLAYOUT_RESOURCE_TYPE_MAX = 3,
};

